name: Prepare local environment
description: Prepare local environment for development by setup node, patch hosts file, and cache dependencies
inputs:
  docker-hub-username:
    description: 'DOCKER_HUB_USERNAME'
    required: true
  docker-hub-access-token:
    description: 'DOCKER_HUB_ACCESS_TOKEN'
    required: true
  push:
    description: Specifies if docker result should be pushed
    required: false
    default: 'false'
outputs:
  docker-build-digest:
    description: Docker build digest
    value: ${{ steps.docker-build.outputs.digest }}
runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker-hub-username }}
        password: ${{ inputs.docker-hub-access-token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: ${{ inputs.push == 'true' }}
        tags: ${{ inputs.docker-hub-username }}/budget-tracker-be:latest
