name: Lint, Test and Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prepare-dependencies:
    name: Prepare local deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: prepare-env
        uses: ./.github/actions/prepare-local-env
      - name: Install dependencies
        if: steps.prepare-env.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    name: Lint source code
    needs: prepare-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-local-env
      - name: Lint source code
        run: npm run lint

  unit-tests:
    name: Unit testing
    needs: prepare-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-local-env
      - name: Unit testing
        run: npm run test:unit

  docker-build:
    name: Build source code using Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/docker-build
        with:
          docker-hub-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker-hub-access-token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
